### ISSUE TITLE
Add mingw-w64-qt5-serialport

### ISSUE THREAD

**Issue by positron96** [haffmans/docker-mingw-qt5#1]
Hello. Could you add mingw-w64-qt5-serialport to a list of installed packages? Or show a way to install it into a running image?

**Comment by haffmans** [comment]
Sorry I've totally missed looking at issues here for all that time... but it should be part of the image now, along with several other Qt-related packages.

To install packages in a running container, use pacman (see the Dockerfile for examples installing most packages so far).
